{"uuid": "a8d44b31-9bb4-4130-9ef9-1646a013b39d", "children": ["181d329b-29f0-4c45-8da0-a48004d6b843"], "befores": [{"name": "test", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\n\n", "trace": "  File \"d:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python\\PyCharm Community Edition 2019.2.3\\A+6.0 project\\case\\test_device_nologin.py\", line 19, in test\n    deviceProject(driver).login_y_n()\n  File \"D:\\Python\\PyCharm Community Edition 2019.2.3\\A+6.0 project\\page\\page_device\\device_nologin.py\", line 36, in login_y_n\n    a = deviceProject.get_text(self, self.device_button1)\n  File \"D:\\Python\\PyCharm Community Edition 2019.2.3\\A+6.0 project\\common\\public.py\", line 21, in get_text\n    return self.driver.find_element_by_id(id).text\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in find_element_by_id\n    return self.find_element(by=By.ID, value=id_)\n  File \"d:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 276, in find_element\n    'value': value})['value']\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"d:\\python\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1614669496514, "stop": 1614669564453}], "start": 1614669496514, "stop": 1614669564492}